import { useState, useRef, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";
import { Upload, FileText, Loader2, ShieldCheck, AlertTriangle } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import DOMPurify from "dompurify";

const PROJECT_TYPES = [
  "Rear Extension",
  "Loft Conversion",
  "Full Rewire",
  "Bathroom",
  "Kitchen",
  "Boiler/Heating Replacement",
  "New Build",
  "Roofing",
  "Other",
];

const DisclaimerBanner = () => (
  <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 flex gap-3 items-start">
    <AlertTriangle className="h-5 w-5 text-amber-600 shrink-0 mt-0.5" />
    <div className="font-mono text-xs text-amber-800 leading-relaxed space-y-1">
      <p className="font-semibold">Important Disclaimer</p>
      <p>
        This analysis is generated by AI and is provided as general guidance only. It is not a professional survey, 
        valuation, or formal quotation. Cost estimates are indicative ranges based on typical UK construction market 
        rates and may not reflect exact pricing in your area or for your specific project. ProGrafter accepts no 
        liability for decisions made based on this report. Always obtain independent professional advice before 
        committing to any building work.
      </p>
    </div>
  </div>
);

const QuoteCheckerForm = ({ onSubmitted }: { onSubmitted: (id: string, email: string, lookupToken: string) => void }) => {
  const [file, setFile] = useState<File | null>(null);
  const [projectType, setProjectType] = useState("");
  const [email, setEmail] = useState("");
  const [postcode, setPostcode] = useState("");
  const [description, setDescription] = useState("");
  const [website, setWebsite] = useState(""); // honeypot — must stay empty
  const [isSubmitting, setIsSubmitting] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = e.target.files?.[0];
    if (selected && selected.type === "application/pdf") {
      if (selected.size > 10 * 1024 * 1024) {
        toast({ title: "File too large", description: "Maximum file size is 10MB.", variant: "destructive" });
        return;
      }
      setFile(selected);
    } else {
      toast({ title: "Invalid file", description: "Please upload a PDF file.", variant: "destructive" });
    }
  };

  const handleSubmit = async () => {
    if (!file || !projectType || !email || description.length < 30) {
      toast({ title: "Missing fields", description: "Please fill in all required fields. Description must be at least 30 characters.", variant: "destructive" });
      return;
    }
    setIsSubmitting(true);
    try {
      // Upload PDF
      const fileName = `${Date.now()}-${file.name}`;
      const { error: uploadError } = await supabase.storage
        .from("quote-pdfs")
        .upload(fileName, file, { contentType: "application/pdf" });
      if (uploadError) throw uploadError;

      // Create record
      const { data: record, error: insertError } = await supabase
        .from("quote_checks")
        .insert({ email, project_type: projectType, postcode, description, pdf_url: fileName })
        .select("id, lookup_token")
        .single();
      if (insertError) throw insertError;

      // Create Stripe checkout session (passes honeypot through)
      const { data: checkoutData, error: checkoutError } = await supabase.functions.invoke(
        "create-quote-checkout",
        { body: { quoteCheckId: record.id, email, website } }
      );
      if (checkoutError) throw checkoutError;

      if (checkoutData?.url) {
        // Store quote ID + lookup token for when they return
        localStorage.setItem(
          "pendingQuoteCheck",
          JSON.stringify({ id: record.id, email, lookupToken: (record as any).lookup_token }),
        );
        // Use top-level navigation so the redirect works inside iframes (e.g. Lovable preview)
        if (window.top && window.top !== window.self) {
          window.top.location.href = checkoutData.url;
        } else {
          window.location.href = checkoutData.url;
        }
      } else {
        throw new Error("No checkout URL returned");
      }
    } catch (err: any) {
      console.error(err);
      toast({ title: "Something went wrong", description: err.message || "Please try again.", variant: "destructive" });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="space-y-6">
      <DisclaimerBanner />
      <div className="bg-card rounded-2xl border border-border p-6 md:p-8 space-y-6 shadow-sm">
        <div className="space-y-2">
          <Label className="font-mono text-sm text-navy">Quote PDF *</Label>
          <div
            onClick={() => fileInputRef.current?.click()}
            className="border-2 border-dashed border-border rounded-xl p-8 text-center cursor-pointer hover:border-teal/50 transition-colors"
          >
            <input ref={fileInputRef} type="file" accept=".pdf" onChange={handleFileChange} className="hidden" />
            {file ? (
              <div className="flex items-center justify-center gap-3">
                <FileText className="h-8 w-8 text-teal" />
                <div className="text-left">
                  <p className="font-mono text-sm text-navy font-medium">{file.name}</p>
                  <p className="font-mono text-xs text-muted-foreground">
                    {(file.size / 1024 / 1024).toFixed(1)}MB — Click to change
                  </p>
                </div>
              </div>
            ) : (
              <div>
                <Upload className="mx-auto h-8 w-8 text-muted-foreground mb-2" />
                <p className="font-mono text-sm text-muted-foreground">Click to upload your quote PDF</p>
                <p className="font-mono text-xs text-muted-foreground mt-1">PDF only — Max 10MB</p>
              </div>
            )}
          </div>
        </div>

        <div className="space-y-2">
          <Label className="font-mono text-sm text-navy">Project Type *</Label>
          <Select value={projectType} onValueChange={setProjectType}>
            <SelectTrigger className="font-mono"><SelectValue placeholder="Select project type" /></SelectTrigger>
            <SelectContent>
              {PROJECT_TYPES.map((type) => (
                <SelectItem key={type} value={type} className="font-mono">{type}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-2">
          <Label className="font-mono text-sm text-navy">Postcode</Label>
          <Input type="text" placeholder="e.g. SW1A 1AA" value={postcode} onChange={(e) => setPostcode(e.target.value)} className="font-mono" />
        </div>

        <div className="space-y-2">
          <Label className="font-mono text-sm text-navy">What did you ask to be quoted for? *</Label>
          <textarea
            placeholder="e.g. Single storey rear extension, 4m x 3m, with bi-fold doors..."
            value={description} onChange={(e) => setDescription(e.target.value)} rows={3}
            className="flex w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 font-mono resize-none"
          />
          <p className="font-mono text-xs text-muted-foreground">Minimum 30 characters ({description.length}/30)</p>
        </div>

        <div className="space-y-2">
          <Label className="font-mono text-sm text-navy">Email Address *</Label>
          <Input type="email" placeholder="you@example.com" value={email} onChange={(e) => setEmail(e.target.value)} className="font-mono" />
          <p className="font-mono text-xs text-muted-foreground">Your report will be delivered here.</p>
        </div>

        {/* Honeypot — hidden from real users, bots will fill it */}
        <div
          aria-hidden="true"
          style={{ position: "absolute", left: "-10000px", top: "auto", width: "1px", height: "1px", overflow: "hidden" }}
        >
          <label htmlFor="website">Website (leave blank)</label>
          <input
            id="website"
            name="website"
            type="text"
            tabIndex={-1}
            autoComplete="off"
            value={website}
            onChange={(e) => setWebsite(e.target.value)}
          />
        </div>

        <Button
          onClick={handleSubmit}
          disabled={isSubmitting || !file || !projectType || !email || description.length < 30}
          className="w-full h-12 bg-teal text-white font-mono text-sm rounded-xl hover:bg-teal-hover transition-colors shadow-lg shadow-teal/20 disabled:bg-muted disabled:text-muted-foreground disabled:shadow-none disabled:opacity-60"
        >
          {isSubmitting ? (
            <span className="flex items-center gap-2"><Loader2 className="h-4 w-4 animate-spin" />Preparing checkout...</span>
          ) : (
            "Check My Quote — £49"
          )}
        </Button>
        <p className="text-center font-mono text-xs text-muted-foreground">
          Secure payment via Stripe. Your report is generated in under 60 seconds.
        </p>
      </div>
    </div>
  );
};

const QuoteCheckerResult = ({
  quoteCheckId,
  email,
  lookupToken,
}: {
  quoteCheckId: string;
  email: string;
  lookupToken: string;
}) => {
  const [reportHtml, setReportHtml] = useState<string | null>(null);
  const [status, setStatus] = useState<string>("pending");

  useEffect(() => {
    let cancelled = false;
    const poll = async () => {
      while (!cancelled) {
        const { data, error } = await supabase.functions.invoke("read-quote-check", {
          body: { quoteCheckId, lookupToken },
        });
        if (!cancelled && !error && data) {
          setStatus(data.status);
          if (data.status === "complete" && data.report_html) {
            setReportHtml(data.report_html);
            return;
          }
          if (data.status === "error") return;
        }
        await new Promise((r) => setTimeout(r, 3000));
      }
    };
    poll();
    return () => { cancelled = true; };
  }, [quoteCheckId, lookupToken]);

  if (status === "error") {
    return (
      <div className="text-center py-12">
        <p className="font-mono text-sm text-destructive">Something went wrong analysing your quote. Please try again.</p>
      </div>
    );
  }

  if (!reportHtml) {
    return (
      <div className="text-center py-16 space-y-4">
        <Loader2 className="mx-auto h-10 w-10 text-teal animate-spin" />
        <h2 className="font-heading text-2xl text-navy">Analysing your quote…</h2>
        <p className="font-mono text-sm text-muted-foreground max-w-md mx-auto leading-relaxed">
          Running our 43-point checklist against your quote. This usually takes around 60 seconds.
        </p>
      </div>
    );
  }

  const sanitizedHtml = DOMPurify.sanitize(reportHtml, {
    USE_PROFILES: { html: true },
    FORBID_TAGS: ["script", "style", "iframe", "object", "embed", "form", "input"],
    FORBID_ATTR: ["onerror", "onload", "onclick", "onmouseover", "onfocus", "onblur", "onchange", "onsubmit"],
  });

  return (
    <div className="space-y-6">
      <div className="text-center">
        <h2 className="font-heading text-2xl text-navy mb-1">Your Quote Analysis</h2>
        <p className="font-mono text-xs text-muted-foreground">Report also sent to {email}</p>
      </div>
      <DisclaimerBanner />
      <div
        className="bg-card rounded-2xl border border-border p-6 md:p-8 shadow-sm prose prose-sm max-w-none font-mono
          [&_h1]:font-heading [&_h1]:text-navy [&_h1]:text-xl
          [&_h2]:font-heading [&_h2]:text-navy [&_h2]:text-lg [&_h2]:mt-6
          [&_h3]:font-heading [&_h3]:text-navy [&_h3]:text-base
          [&_table]:w-full [&_th]:text-left [&_th]:p-2 [&_td]:p-2 [&_tr]:border-b [&_tr]:border-border"
        dangerouslySetInnerHTML={{ __html: sanitizedHtml }}
      />
      <DisclaimerBanner />
    </div>
  );
};

const QuoteChecker = () => {
  const [result, setResult] = useState<{ id: string; email: string; lookupToken: string } | null>(null);
  const [searchParams] = useSearchParams();
  const { toast } = useToast();
  const [verifying, setVerifying] = useState(false);

  // Handle return from Stripe checkout
  useEffect(() => {
    const sessionId = searchParams.get("session_id");
    const quoteId = searchParams.get("quote_id");
    const cancelled = searchParams.get("cancelled");

    if (cancelled) {
      toast({ title: "Payment cancelled", description: "Your quote check was not processed.", variant: "destructive" });
      // Clean URL
      window.history.replaceState({}, "", "/quote-checker");
      return;
    }

    if (sessionId && quoteId) {
      setVerifying(true);
      const verify = async () => {
        try {
          const { data, error } = await supabase.functions.invoke("verify-quote-payment", {
            body: { sessionId, quoteCheckId: quoteId },
          });
          if (error) throw error;
          if (data?.paid) {
            const stored = localStorage.getItem("pendingQuoteCheck");
            const parsed = stored ? JSON.parse(stored) : {};
            const email = parsed.email || "";
            const lookupToken = parsed.lookupToken || "";
            localStorage.removeItem("pendingQuoteCheck");
            if (!lookupToken) {
              toast({
                title: "Session expired",
                description: "We couldn't find your secure access token. Please check your email for the report link.",
                variant: "destructive",
              });
              window.history.replaceState({}, "", "/quote-checker");
              return;
            }
            setResult({ id: quoteId, email, lookupToken });
            window.history.replaceState({}, "", "/quote-checker");
          } else {
            toast({ title: "Payment not confirmed", description: "Please try again.", variant: "destructive" });
          }
        } catch (err: any) {
          console.error(err);
          toast({ title: "Verification failed", description: err.message || "Please contact support.", variant: "destructive" });
        } finally {
          setVerifying(false);
        }
      };
      verify();
    }
  }, [searchParams, toast]);

  if (verifying) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="pt-24 pb-16 px-6">
          <div className="max-w-2xl mx-auto text-center py-16 space-y-4">
            <Loader2 className="mx-auto h-10 w-10 text-teal animate-spin" />
            <h2 className="font-heading text-2xl text-navy">Confirming your payment…</h2>
            <p className="font-mono text-sm text-muted-foreground">Please wait while we verify your payment and start your analysis.</p>
          </div>
        </div>
        <Footer />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <SEO
        title="AI Quote Checker — ProGrafter | Check Any Building Quote for £49"
        description="Upload any building quote. Our AI checks it against a 43-point checklist and identifies missing items before you sign. Report delivered to your inbox within 2 minutes. £49."
        path="/quote-checker"
      />
      <Navbar />
      <div className="pt-24 pb-16 px-6">
        <div className="max-w-2xl mx-auto">
          <div className="text-center mb-10">
            <div className="inline-flex items-center gap-2 bg-teal/10 text-teal font-mono text-xs px-3 py-1.5 rounded-full mb-4">
              <ShieldCheck className="h-3.5 w-3.5" />
              43-Point Quote Analysis
            </div>
            <h1 className="font-heading text-4xl md:text-5xl text-navy mb-3">AI Quote Checker</h1>
            <p className="text-muted-foreground font-mono text-sm max-w-md mx-auto leading-relaxed">
              Upload any building quote. Our AI checks it against a 43-point checklist and tells you exactly what's missing. Report in your inbox within 2 minutes. <span className="font-semibold text-navy">£49.</span>
            </p>
          </div>

          {result ? (
            <QuoteCheckerResult quoteCheckId={result.id} email={result.email} lookupToken={result.lookupToken} />
          ) : (
            <QuoteCheckerForm onSubmitted={(id, email, lookupToken) => setResult({ id, email, lookupToken })} />
          )}
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default QuoteChecker;
