// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful to verify connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/get-platform-overview.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_platform_overview_default = defineTool2({
  name: "get_platform_overview",
  title: "Get platform overview",
  description: "Return an overview of ProGrafter: what it is, who it's for (trades and homeowners), and how it works.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "ProGrafter is a premium UK construction trust platform (not a trades directory).",
          "",
          "For homeowners: post a job, receive quotes from verified trades, use the AI Quote Checker to audit quotes, then manage the project (stages, payments, variations, messaging) end-to-end.",
          "",
          "For trades: get matched to relevant local jobs, submit quotes, and run projects with stage payments, variations, site updates and messaging.",
          "",
          "Trust is platform-wide: 5-Step Trade Verification, Homeowner Verification, Two-Way Reviews, Manual Job Review, Privacy & Security, AI Transparency, Fair Pricing and Dispute Resolution. See the Trust Centre at https://prografter.co.uk/trust."
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_pricing_default = defineTool3({
  name: "get_pricing",
  title: "Get pricing information",
  description: "Return how ProGrafter pricing works for trades and homeowners (commission model, job posting, AI Quote Checker).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "ProGrafter pricing overview. For live figures always refer to https://prografter.co.uk/pricing.",
          "",
          "- Homeowners: posting a job and receiving quotes is free.",
          "- Trades: a fair, transparent commission model with no lock-in.",
          "- AI Quote Checker: audits a homeowner's quote for clarity, VAT, scope and project-control gaps.",
          "",
          "Full, current pricing details and terms are published on the pricing page."
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "prografter-mcp",
  title: "ProGrafter MCP",
  version: "0.1.0",
  instructions: "Tools for ProGrafter, a UK construction trust platform. Use `get_platform_overview` to learn what ProGrafter is and how it works, `get_pricing` for the pricing model, and `echo` to verify connectivity.",
  tools: [get_platform_overview_default, get_pricing_default, echo_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
