ALTER TABLE public.scraped_trades
  ADD COLUMN IF NOT EXISTS website_status text,
  ADD COLUMN IF NOT EXISTS website_score integer,
  ADD COLUMN IF NOT EXISTS opportunity_angle text,
  ADD COLUMN IF NOT EXISTS main_website_issue text,
  ADD COLUMN IF NOT EXISTS audit_notes text,
  ADD COLUMN IF NOT EXISTS audit_sent boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS audit_sent_date date,
  ADD COLUMN IF NOT EXISTS proposal_sent_bool boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS proposal_sent_date date,
  ADD COLUMN IF NOT EXISTS package_recommended text,
  ADD COLUMN IF NOT EXISTS quoted_value numeric,
  ADD COLUMN IF NOT EXISTS monthly_care_interest text,
  ADD COLUMN IF NOT EXISTS monthly_care_price numeric,
  ADD COLUMN IF NOT EXISTS contact_name text,
  ADD COLUMN IF NOT EXISTS contact_email text,
  ADD COLUMN IF NOT EXISTS whatsapp_number text,
  ADD COLUMN IF NOT EXISTS preferred_contact_method text,
  ADD COLUMN IF NOT EXISTS tps_checked boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS ctps_checked boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS date_checked date,
  ADD COLUMN IF NOT EXISTS do_not_call boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS objection_reason text,
  ADD COLUMN IF NOT EXISTS source_of_number text,
  ADD COLUMN IF NOT EXISTS last_contacted_date date,
  ADD COLUMN IF NOT EXISTS next_follow_up_date date,
  ADD COLUMN IF NOT EXISTS call_attempts integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_call_outcome text,
  ADD COLUMN IF NOT EXISTS lost_reason text;